"""Receipt rendering helpers for printable booking PDFs."""

from __future__ import annotations

from textwrap import wrap

from app.models.booking import Booking
from app.models.payment import Payment
from app.services.serializers import booking_to_dict, house_to_dict, payment_to_dict


def receipt_filename(booking_id: str) -> str:
    return f"unistay-receipt-{booking_id}.pdf"


def build_receipt_payload(booking: Booking, payment: Payment | None = None) -> dict:
    return {
        "booking": booking_to_dict(booking),
        "studentName": booking.student.full_name,
        "studentEmail": booking.student.email,
        "house": house_to_dict(booking.house) if booking.house else None,
        "room": {
            "id": booking.room.id,
            "type": booking.room.type,
            "rent": booking.room.rent,
            "deposit": booking.room.deposit,
        }
        if booking.room
        else None,
        "payment": payment_to_dict(payment) if payment else None,
    }


def render_receipt_pdf(receipt: dict) -> bytes:
    """Render a booking receipt dictionary as a simple printable PDF.

    This intentionally uses a tiny PDF writer instead of a third-party package
    so receipt generation works in slow/offline development environments.
    """
    lines: list[tuple[str, int, int]] = []

    def text(value) -> str:
        return "" if value is None else str(value)

    def money(value) -> str:
        if value in (None, ""):
            return "ZMW 0"
        return f"ZMW {value}"

    def add(value: str, *, size: int = 10, gap: int = 14) -> None:
        lines.append((value, size, gap))

    def line(label: str, value) -> None:
        add(f"{label}: {text(value)}")

    def section(title: str) -> None:
        add("", gap=10)
        add(title.upper(), size=13, gap=18)

    booking = receipt.get("booking") or {}
    house = receipt.get("house") or {}
    room = receipt.get("room") or {}
    payment = receipt.get("payment") or {}

    add("UniStay Receipt", size=24, gap=28)
    add("Printable booking receipt", size=10, gap=22)

    section("Booking")
    line("Receipt number", booking.get("id"))
    line("Booking status", booking.get("status"))
    line("Created", booking.get("createdAt"))
    line("Move-in date", booking.get("moveInDate"))

    section("Student")
    line("Name", receipt.get("studentName"))
    line("Email", receipt.get("studentEmail"))

    section("Accommodation")
    line("House", house.get("name"))
    line("Location", house.get("location"))
    line("Room type", room.get("type"))
    line("Rent", money(room.get("rent")))
    line("Deposit", money(room.get("deposit")))

    section("Payment")
    line("Reference", payment.get("reference") or "Not paid yet")
    line("Status", payment.get("status") or "unpaid")
    line("Amount", money(payment.get("amount") or room.get("rent")))
    line("Currency", payment.get("currency") or "ZMW")
    line("Method", payment.get("paymentType") or "N/A")

    note = booking.get("note")
    if note:
        section("Note")
        for wrapped in wrap(text(note), width=85):
            add(wrapped)

    add("", gap=18)
    add(
        "This receipt was generated by UniStay. Keep it for your records.",
        size=8,
    )
    return _build_pdf(lines, title=f"UniStay Receipt {booking.get('id', '')}")


def _escape_pdf_text(value: str) -> str:
    safe = value.encode("latin-1", "replace").decode("latin-1")
    return safe.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _build_pdf(lines: list[tuple[str, int, int]], *, title: str) -> bytes:
    y = 792
    commands = ["BT"]
    for value, size, gap in lines:
        y -= gap
        commands.append(f"/F1 {size} Tf")
        commands.append(f"50 {y} Td ({_escape_pdf_text(value)}) Tj")
        commands.append(f"-50 {-y} Td")
    commands.append("ET")
    stream = "\n".join(commands).encode("latin-1")
    title_text = _escape_pdf_text(title)

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
            b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>"
        ),
        b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n"
        + stream
        + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        f"<< /Title ({title_text}) /Producer (UniStay API) >>".encode("latin-1"),
    ]

    output = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(output))
        output.extend(f"{index} 0 obj\n".encode("ascii"))
        output.extend(obj)
        output.extend(b"\nendobj\n")

    xref_offset = len(output)
    output.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    output.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    output.extend(
        (
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R /Info 6 0 R >>\n"
            f"startxref\n{xref_offset}\n%%EOF\n"
        ).encode("ascii")
    )
    return bytes(output)
